services:
  db:
    image: postgres:15-alpine
    container_name: document-system-db
    environment:
      - POSTGRES_DB=document_registry_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d document-registry_db"]
      interval: 5s
      timeout: 5s
      retries: 5
